name: Deploy new version

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  APP_NAME: TSM_PicoW_CI_CD

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy firmware
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t tsmcicd-image .

      - name: Create Docker container
        run: docker create --name tsmcicd-container tsmcicd-image

      - name: Copy out Intel Hex file
        run: docker cp tsmcicd-container:/project/build/${{ env.APP_NAME }}.hex ./firmware.hex

      - name: Put app name into env context
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firmware.hex
          body_path: CHANGELOG.md
